# Efektywne programowanie w języku Python 

## wykład 10

![alt text](images/numpy_project_page.jpg "numpy")

## Wydajne obliczenia numeryczne

Standardowe typy danych i procedury Pythona nie nadają się do poważnych zastosowań numerycznych. Konieczne było opracowanie zoptymalizowanych pod względem typowych operacji numerycznych typów danych i procedur. Stworzony został **Numerical Python**, zwany w skrócie **NumPy**. Podczas rozwoju tego pakietu kierowano się podejściem zastosowanym w takich językach jak Basis, MATLAB, rodzina języków APL, FORTRAN i innych. Tak więc NumPy jest biblioteką Pythona służącą do obliczeń naukowych. Dostarcza ona listę matematycznych funkcji użytecznych w takich zagadnieniach jak:
- algebra liniowa,
- transformacje Fouriera,
- generowanie liczb losowych,
- oraz wszystkie operacje na tablicach i macierzach, które są podstawowymi obiektami w Numpy.

In [3]:
import numpy
# lub
import numpy as np 

## Tworzenie macierzy

Do stworzenia tablicy jedno-, dwu- i wielowymiarowej używamy funkcji **array**:

In [8]:
x = np.array([1,2,3]) # tablica jednowymiarowa
A = np.array([[1,2,3] , [4,5,6]]) # tablica dwuwymiarowa
B = np.array( [[[1,1,1],[1,1,1]], [[2,2,2],[2,2,2]]]) # wielowymiarowa

print('x=',  x, '\n')
print('A=', A, '\n')
print('B=', B, '\n')

x= [1 2 3] 

A= [[1 2 3]
 [4 5 6]] 

B= [[[1 1 1]
  [1 1 1]]

 [[2 2 2]
  [2 2 2]]] 



Przy tworzeniu tablicy istnieje możliwość zadeklarowania jej typu:

In [9]:
z = np.array( [[1,0], [0,1]], dtype=complex) # tablica liczb zespolonych
print(z)

[[ 1.+0.j  0.+0.j]
 [ 0.+0.j  1.+0.j]]


Do tworzenia tablicy jednowymiarowej (wektora) składającego się z elementów z danego zakresu używamy polecenia **arange(start, stop, krok)**:

In [10]:
print(np.arange(10), '\n')
print(np.arange(0, 10, 2), '\n')
print(np.arange(0., 10, 0.5))

[0 1 2 3 4 5 6 7 8 9] 

[0 2 4 6 8] 

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.
  7.5  8.   8.5  9.   9.5]


Jeśli chcemy wygenerować tablicę o określonej liczbie z danego przedziału, używamy funkcji linspace:

In [14]:
print(np.linspace(0., 10., 3), '\n')
print(np.linspace(0., 1., 5))

[  0.   5.  10.] 

[ 0.    0.25  0.5   0.75  1.  ]


Biblioteka Numpy oferuje wiele możliwości budowania typowych tablic:

In [15]:
print(np.ones((3,3)), '\n') # dwuwymiarowa tablica (3x3) wypełniona jedynkami
print(np.zeros((3,2)), '\n') # dwuwymiarowa tablica (3x2) wypełniona zerami
print(np.eye(4)) # macierz jednostkowa 4x4

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]] 

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]] 

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


Korzystając z powyższych funkcji możemy w łatwy sposób tworzyć dowolne macierze, zmieniając ich rozmiary.

In [16]:
print(np.arange(15).reshape(5,3), '\n')
print(np.linspace(0., 1, 15).reshape(5,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] 

[[ 0.          0.07142857  0.14285714]
 [ 0.21428571  0.28571429  0.35714286]
 [ 0.42857143  0.5         0.57142857]
 [ 0.64285714  0.71428571  0.78571429]
 [ 0.85714286  0.92857143  1.        ]]


## Operacje na indeksach

In [18]:
x = np.arange(15)
print(x, '\n')
print(x[3], '\n')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 

3 



In [19]:
A = np.arange(20).reshape(5,4)
print(A, '\n')
print(A[2, 3])
print(A[2][3], '\n') # równoważnie
print(A[2], '\n') # trzeci wiersz
print(A[:, 2]) # trzecia kolumna

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]] 

11
11 

[ 8  9 10 11] 

[ 2  6 10 14 18]


Aby wyświetlić fragment tablicy od  `n−1`  do `m−1`  elementów używamy składni: `tablica[n:m]`, analogicznie aby wyświetlić elementy tablicy pomiędzy  `n−1` , a  `m−1`  przesuwając się o wartość  `k`  używamy składni `tablica[n:m:k]`.

In [17]:
x = np.arange(15)
print(x, '\n')
print(x[3:11], '\n')
print(x[3:11:2], '\n')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 

[ 3  4  5  6  7  8  9 10] 

[3 5 7 9] 



In [20]:
A = np.arange(20).reshape(5,4)
print(A[2:4], '\n') # wiersze od trzeciego do czwartego
print(A[:,2:4], '\n') # trzecia i czwarta kolumnę
print(A[:,[2,3]]) # równoważnie

[[ 8  9 10 11]
 [12 13 14 15]] 

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]] 

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]]


Tablice można też budować w oparciu o już istniejące:

In [ ]:
A = np.arange(20).reshape(5,4)
print(A, '\n')

B = A[2:4, 2:]
print(B)

## Zmiana rozmiaru, kształtu tablicy

Do zmiany rozmiaru tablicy już utworzonej służy funkcja: **reshape**. Operacja ta nie zmieni zawartości oryginalnej tablicy, pokaże jedynie jej elementy w zadanej postaci.

In [ ]:
A = np.arange(8)
print(A,'\n')
print(A.reshape((2, 4)), '\n')
print(A)

Aby zmienić kształt tablicy za pomocą funkcji reshape możemy zrobić tak:

In [ ]:
A = np.arange(8)
print(A,'\n')
A = A.reshape((2, 4))
print(A)

lub użyć funkcję resize:

In [ ]:
A = np.arange(8)
print(A,'\n')
A.resize(2, 4)
# print(A.resize(2, 4), '\n')
print(A)

Do sprawdzenia wymiaru tablicy służy funkcja **shape**:

In [ ]:
A = np.arange(20).reshape(5,4)
print(A.shape, '\n') # wymiar tablicy
print(A.shape[0], '\n') # pierwszy wymiar
print(A.shape[1], '\n') # drugi wymiar
print(A.size) # liczba wszystkich elementów w tablicy 

Transpozycja macierzy:

In [ ]:
A = np.arange(8).reshape(2,4)
print(A, '\n')
print(A.T, '\n')
print(np.transpose(A))

Podobnie jak przy funkcji `reshape` aby zachować wynik transpozycji macierzy musimy go przypisać do nowej zmiennej.

Aby zmienić tablicę na jednowymiarową, możemy użyć polecenia:

In [23]:
A = np.arange(8).reshape(2,4)
print(A, '\n')
print(np.ravel(A), '\n')
print(A.reshape(-1,))

[[0 1 2 3]
 [4 5 6 7]] 

[0 1 2 3 4 5 6 7] 

[0 1 2 3 4 5 6 7]


## Dodawanie, usuwanie elementów

Do dodania elementu, kolumny lub wiersza do tablicy w ustalonej pozycji/lokalizacji używamy polecenia **insert**:

In [24]:
A = np.array([[1, 1], [2, 2], [3, 3]])
print(A, '\n')
print(np.insert(A, 1, 5), '\n')
print(A, '\n')
print(np.insert(A, 1, 5, axis=1), '\n') # wstawienie drugiej kolumny
print(np.insert(A, 1, [4, 5, 6], axis=1), '\n') # wstawienie drugiej kolumny
print(np.insert(A, 3, 4, axis=0)) # wstawienie wiersza kolumny

[[1 1]
 [2 2]
 [3 3]] 

[1 5 1 2 2 3 3] 

[[1 1]
 [2 2]
 [3 3]] 

[[1 5 1]
 [2 5 2]
 [3 5 3]] 

[[1 4 1]
 [2 5 2]
 [3 6 3]] 

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.insert.html

Aby dodać element(-y) na koniec tablicy należy użyć funkcji **append**:

In [25]:
print(np.append([1, 2, 3], [4, 5, 6]), '\n')
print(np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]]), '\n')
print(np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0))

[1 2 3 4 5 6] 

[1 2 3 4 5 6 7 8 9] 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Biblioteka NumPy umożliwia nam także usuwanie wybranych elementów, wierszy lub kolumn z tablicy:

In [26]:
A = np.arange(20).reshape(5,4)
print(A, '\n')

print(np.delete(A, 1, axis=0), '\n')
print(A, '\n')
print(np.delete(A, [1, 2], 1), '\n')
print(np.delete(A, [1, 2, 5, 7, 9, 12, 17, 19]))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]] 

[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]] 

[[ 0  3]
 [ 4  7]
 [ 8 11]
 [12 15]
 [16 19]] 

[ 0  3  4  6  8 10 11 13 14 15 16 18]


## Podstawowe operacje na tablicach

### Dodawanie

In [31]:
x = np.array([1,4,6,2,5])
v = np.arange(5)
print(x+v)
print(np.add(x, v)) # równoważnie
print(x+1, '\n')

A = np.arange(15, 30).reshape((5, 3))
B = np.arange(15).reshape((5, 3))
print(A+B)
print(np.add(A, B))
print(A+5, '\n')

x = np.array([1,2,3])
print(A, '\n')
print(x, '\n')
print(np.add(A, x)) # dodawanie do każdego wiersza wektora x

[1 5 8 5 9]
[1 5 8 5 9]
[2 5 7 3 6] 

[[15 17 19]
 [21 23 25]
 [27 29 31]
 [33 35 37]
 [39 41 43]]
[[15 17 19]
 [21 23 25]
 [27 29 31]
 [33 35 37]
 [39 41 43]]
[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]] 

[[15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]] 

[1 2 3] 

[[16 18 20]
 [19 21 23]
 [22 24 26]
 [25 27 29]
 [28 30 32]]


### Odejmowanie

In [30]:
x = np.array([1,4,6,2,5])
v = np.arange(5)
print(x-v)
print(np.subtract(x, v)) # równoważnie
print(x-1, '\n')

A = np.arange(15, 30).reshape((5, 3))
B = np.arange(15).reshape((5, 3))
print(A-B)
print(np.subtract(A, B))
print(A-1, '\n')

x = np.array([1,2,3])
print(np.subtract(A, x)) # odjęcie od każdego wiersza wektora x

[ 1  3  4 -1  1]
[ 1  3  4 -1  1]
[0 3 5 1 4] 

[[15 15 15]
 [15 15 15]
 [15 15 15]
 [15 15 15]
 [15 15 15]]
[[15 15 15]
 [15 15 15]
 [15 15 15]
 [15 15 15]
 [15 15 15]]
[[14 15 16]
 [17 18 19]
 [20 21 22]
 [23 24 25]
 [26 27 28]] 

[[14 14 14]
 [17 17 17]
 [20 20 20]
 [23 23 23]
 [26 26 26]]


### Mnożenie

In [32]:
x = np.array([1,4,6,2,5])
v = np.arange(5)
print(x*5, '\n')
print(np.dot(x,v), '\n') # iloczyn skalarny
print(x*v, '\n') # to nie, mnożony jest element przez element! 

A = np.array([[1, 3], [0, 6]])
print(A*5, '\n')

B = np.array([[-2, 6], [8, -2]])
print(np.dot(A, B), '\n')
print(A*B) # to nie, mnożony jest element przez element! 

[ 5 20 30 10 25] 

42 

[ 0  4 12  6 20] 

[[ 5 15]
 [ 0 30]] 

[[ 22   0]
 [ 48 -12]] 

[[ -2  18]
 [  0 -12]]


# UWAGA NA MNOŻENIE MACIERZY

In [33]:
A = np.matrix( ((2,3), (3, 5)) )
B = np.matrix( ((1,2), (5, -1)) )

print(A * B, '\n')
print(np.dot(A, B))

[[17  1]
 [28  1]] 

[[17  1]
 [28  1]]


### Potęgowanie

In [34]:
x = np.array([1,4,6,2,5])
print(x, '\n')

print(x**2)
print(np.power(x, 2), '\n') # równoważnie

A = np.arange(9).reshape((3, 3))
print(A, '\n')
print(A**2, '\n') # kwadrat elementów tablicy
print(np.power(A, 2)) # równoważnie

[1 4 6 2 5] 

[ 1 16 36  4 25]
[ 1 16 36  4 25] 

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]] 

[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


Więcej funkcji można znaleźć tutaj https://docs.scipy.org/doc/numpy/reference/routines.math.html

## Porównania elementów tablic

In [35]:
A = np.arange(5, 20).reshape((5, 3))
B = np.arange(15).reshape((5, 3))

print(A < B, '\n')
print(A == A, '\n')
print(A == 17, '\n')
print(np.any( A > 17 ), '\n') # prawdziwe, jeśli każdy element z osobna spełnia warunek 
print(np.all( A > 17 )) # prawdziwe jeśli wszystkie elementy spełniają warunek

[[False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]] 

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]] 

[[False False False]
 [False False False]
 [False False False]
 [False False False]
 [ True False False]] 

True 

False


## Łączenie i dzielenie tablic

Biblioteka NumPy daje nam narzędzia dzięki, którym możemy łączyć i dzielić tablice.

In [36]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

print(x, '\n')
print(y, '\n')

# łączenie wierszowe
print(np.concatenate((x, y), axis=0), '\n')
print(np.vstack((x,y)), '\n')

# łączenie kolumnowe
print(np.concatenate((x,y.T), axis=1), '\n')
print(np.hstack((x,y.T)))

[[1 2]
 [3 4]] 

[[5 6]] 

[[1 2]
 [3 4]
 [5 6]] 

[[1 2]
 [3 4]
 [5 6]] 

[[1 2 5]
 [3 4 6]] 

[[1 2 5]
 [3 4 6]]


Mamy też możliwość podziału tablicy na podtablice:

In [37]:
x = np.arange(9)
print(x, '\n')
print(np.split(x, 3), '\n') # podział na 3 podtablice
print(np.split(x, [2, 4, 7]), '\n') # podział na 4 podtablice o 
                                # wskazanych początkach

x = x.reshape((3, 3))
print(x, '\n')
print(np.split(x, 3, axis=1), '\n')

# podział ze względu na kolumny
x = np.arange(16.0).reshape(4, 4)
print(x, '\n')
print(np.hsplit(x, 2), '\n')
print(np.hsplit(x, [1, 3]), '\n')

# podział ze względu na wiersze
print(np.vsplit(x, 2), '\n')
print(np.vsplit(x, [1, 3]), '\n')

[0 1 2 3 4 5 6 7 8] 

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])] 

[array([0, 1]), array([2, 3]), array([4, 5, 6]), array([7, 8])] 

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])] 

[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]
 [ 12.  13.  14.  15.]] 

[array([[  0.,   1.],
       [  4.,   5.],
       [  8.,   9.],
       [ 12.,  13.]]), array([[  2.,   3.],
       [  6.,   7.],
       [ 10.,  11.],
       [ 14.,  15.]])] 

[array([[  0.],
       [  4.],
       [  8.],
       [ 12.]]), array([[  1.,   2.],
       [  5.,   6.],
       [  9.,  10.],
       [ 13.,  14.]]), array([[  3.],
       [  7.],
       [ 11.],
       [ 15.]])] 

[array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.]]), array([[  8.,   9.,  10.,  11.],
       [ 12.,  13.,  14.,  15.]])] 

[array([[ 0.,  1.,  2.,  3.]]), array([[  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11

## Wybrane metody z algebry linowej

Do części funkcji typowych dla algebry liniowej możemy się odwołać po zaimportowaniu biblioteki **linalg** będącej integralną częścią biblioteki NumPy.

In [38]:
import numpy.linalg as alg 

### Macierz odwrotna

In [39]:
A = np.array([[1., 2.], [3., 4.]])
invA = alg.inv(A)
print(invA)
print(np.dot(A, invA))

[[-2.   1. ]
 [ 1.5 -0.5]]
[[  1.00000000e+00   0.00000000e+00]
 [  8.88178420e-16   1.00000000e+00]]


### Wyznacznik

In [40]:
print(A)
print(alg.det(A))

[[ 1.  2.]
 [ 3.  4.]]
-2.0


### Ślad

In [41]:
print(A)
print(np.trace(A))

[[ 1.  2.]
 [ 3.  4.]]
5.0


### Norma dla macierz lub wektora

In [42]:
print(alg.norm(A)) # Euklidesowa
print(alg.norm(A, 'fro')) # Frobeniusa https://pl.wikipedia.org/wiki/Norma_macierzowa
print(alg.norm(A, np.inf)) # maksimum

print(alg.norm(A, axis=0)) # wierszy
print(alg.norm(A, axis=1)) # kolumn

5.47722557505
5.47722557505
7.0
[ 3.16227766  4.47213595]
[ 2.23606798  5.        ]


### Rozwiązywanie układów równań

In [43]:
# 4*x_1 + x_2 = 10
# 3*x_1 = 7
A = np.array([[4,1], [3,0]])
b = np.array([10,7])
print(np.linalg.solve(A, b))

[ 2.33333333  0.66666667]


### Dekompozycje macierzy

In [44]:
# QR
A = np.array([[0, 1], [1, 1], [1, 1], [2, 1]])
q, r = alg.qr(A)
print(q)
print(r)

[[ 0.          0.8660254 ]
 [-0.40824829  0.28867513]
 [-0.40824829  0.28867513]
 [-0.81649658 -0.28867513]]
[[-2.44948974 -1.63299316]
 [ 0.          1.15470054]]


In [45]:
# SVD
A = np.random.randn(4, 3)
U, s, V = np.linalg.svd(A)
print(U, '\n')
print(s, '\n')
print(V, '\n')

S = np.zeros((4, 3))
S[:3, :3]  = np.diag(s)
print(np.allclose(A, np.dot(U, np.dot(S, V))))

[[-0.37586574  0.85112883  0.27387449 -0.24351061]
 [-0.29205386  0.03586793  0.29577023  0.90881131]
 [-0.87095872 -0.42262904 -0.08990078 -0.23395181]
 [-0.12190321  0.30931843 -0.9107308   0.24501251]] 

[ 3.72551093  0.90897286  0.71484275] 

[[ 0.05909049  0.86742665 -0.49404384]
 [ 0.34658543 -0.48194941 -0.80473803]
 [-0.93615536 -0.12367603 -0.32911607]] 

True


In [46]:
# Cholesky A = L*L^T
A = np.array([[1,2],[2,5]])
L = np.linalg.cholesky(A)
print(L, '\n')

print(np.allclose(A, np.dot(L, L.T)))

[[ 1.  0.]
 [ 2.  1.]] 

True


## Statystyka

NumPy oferuje dużo możliwości generacji liczb losowych. Poniżej podaję niektóre z nich, więcej można znaleźć tutaj https://docs.scipy.org/doc/numpy/reference/routines.random.html

In [47]:
# macierz losowa 3x2 (liczby z przedziału [0, 1)) 
print(np.random.rand(3,2), '\n')

# macierz losowa 2x3 o elementach z rozkładu N(mu, sigma^2) = N(1, 4)
print(2 * np.random.randn(2, 3) + 1, '\n')

# macierz losowa 3x3 o elementach całkowitych z przedziału [0, 5)
print(np.random.randint(5, size=(3, 3)), '\n')

# losowe wybranie 3 liczb z [0, 1, 2, 3, 4]
print(np.random.choice(5, 3, replace=False), '\n')

[[ 0.75835991  0.42535992]
 [ 0.01476139  0.05228756]
 [ 0.58146264  0.88887656]] 

[[-0.04245615 -0.94427586  0.0730043 ]
 [-1.65744097  4.52713789 -2.86093008]] 

[[3 1 3]
 [2 1 1]
 [4 3 3]] 

[1 4 3] 



In [48]:
# rozkład wykładniczy (scale = 1/lambda)
print(numpy.random.exponential(scale=1.0, size=(2, 3)), '\n')

# rozkład geometryczny
print(np.random.geometric(p=0.35, size=(2,4)), '\n')

# rozkład normalny N(mu, sigma)
print(np.random.normal(0.0, 1, size=7), '\n')

# rozkład Poissona
print(np.random.poisson(5, 10), '\n')

[[ 0.47893738  0.0891379   1.276213  ]
 [ 0.68741398  0.14951807  0.21217068]] 

[[1 6 3 2]
 [2 1 4 1]] 

[-0.48277852  0.15538883 -1.28978771  1.37849371  0.79489752  0.04440185
  1.95451666] 

[6 6 6 6 3 5 4 5 8 4] 



In [49]:
# rozkład wielowymiarowy rozkład normalny
mean = [5, -5]
cov = [[10, -6], [-6, 5]]
print(np.random.multivariate_normal(mean, cov, 7), '\n')

[[  2.93034055  -4.09797944]
 [ 11.33324841  -7.68879979]
 [  4.71883054  -3.69641009]
 [  6.68249296  -5.20348005]
 [ 11.52005279 -11.24113105]
 [  3.93200448  -3.75314643]
 [  1.10574138  -2.96820495]] 



### Proste statystyki

In [51]:
x = np.random.normal(2.0, 2.5, size=7)

print(x.max(),'\n') #maksymalna wartość

print(x.min(),'\n') # minimalna wartość 

print(x.sum(),'\n') # suma wszystkich elementów 

print(x.prod(),'\n') # iloczyn wszystkich elementów 

9.13123147739 

-2.02965984177 

15.1940065966 

214.182769285 



In [50]:
print(x.mean()) # średnia z wszystkich elementów
print(np.mean(x),'\n')

print(np.median(x),'\n') # mediana

print(x.std()) # odchylenie standardowe 
print(np.std(x),'\n')

print(x.var()) # wariancja
print(np.var(x))

7.5
7.5 

7.5 

4.60977222865
4.60977222865 

21.25
21.25


In [52]:
A = np.array( [[4, 3, -5, 7], [40, -100, 20, 27], [10, 44, 0, 11]] ) 

print(A,'\n')

print(A.min(),'\n') # najmniejsza wartość w całej tablicy
print(A.max(),'\n') # największa wartość w całej tablicy 

print(A.min(0)) # najmniejsza wartość w każdej z kolumn
print(np.min(A, axis=0),'\n')

print(A.min(1),'\n') # najmniejsza wartość w każdym z wierszy 

print(np.cov(A))

[[   4    3   -5    7]
 [  40 -100   20   27]
 [  10   44    0   11]] 

-100 

44 

[   4 -100   -5    7]
[   4 -100   -5    7] 

[  -5 -100    0] 

[[   26.25          -7.25          34.25      ]
 [   -7.25        4228.91666667 -1163.91666667]
 [   34.25       -1163.91666667   366.91666667]]


## Sortowanie i przeszukiwanie tablicy

Biblioteka NumPy ma także funkcje sortujące elementy tablicy

In [53]:
x = np.random.randint(20, size=10)
print(x,'\n')
print(np.sort(x)) # quicksort
print(np.sort(x, kind='mergesort'), '\n')

[ 9 15  3 19 17  3 16 11 17  5] 

[ 3  3  5  9 11 15 16 17 17 19]
[ 3  3  5  9 11 15 16 17 17 19] 



In [54]:
A = np.array([[1,4],[3,1]]) 
print(A, '\n')
print(np.sort(A), '\n') # sortowanie względem ostatniej osi
print(np.sort(A, axis=0), '\n')
print(np.sort(A, axis=None)) # wszystkich elementów

[[1 4]
 [3 1]] 

[[1 4]
 [1 3]] 

[[1 1]
 [3 4]] 

[1 1 3 4]


In [55]:
dtype = [('name', 'S10'), ('height', float), ('age', int)]
values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38),
          ('Galahad', 1.7, 38)]
A = np.array(values, dtype=dtype)  # tworzenie tablicy strukturalnej
print(A, '\n')
print(np.sort(A, order='height') )

[(b'Arthur',  1.8, 41) (b'Lancelot',  1.9, 38) (b'Galahad',  1.7, 38)] 

[(b'Galahad',  1.7, 38) (b'Arthur',  1.8, 41) (b'Lancelot',  1.9, 38)]


In [56]:
# indeksy posortowanej tablicy
x = np.array([3, 1, 2])
             
print(np.argsort(x), '\n')

A = np.array([[1,4],[3,1]]) 
print(A, '\n')
print(np.argsort(A, axis=1))

[1 2 0] 

[[1 4]
 [3 1]] 

[[0 1]
 [1 0]]


Numpy daje nam możliwość przeszukiwania tablicy:

In [57]:
# znajdowanie indeksu największego elementu w tablicy
A = np.random.randint(20, size=(3, 6))
print(A, '\n')
print(np.argmax(A), '\n') # indeks dla największego elementu w całej tablicy

print(np.argmax(A, axis=0)) # indeksy dla największych elementów w kolumnach

print(np.argmax(A, axis=1)) # indeksy dla największych elementów w wierszach

[[ 8 10 18  5 18 11]
 [15 18 12 10 17  2]
 [ 0  7  5  2 17 15]] 

2 

[1 1 0 1 0 2]
[2 1 4]


Analogicznie jak wyżej można znajdować indeks(-y) dla najmniejszej wartości, korzystając z funkcji argmin.
Można także znajdować indeksy tych elementów tablicy, które spełniają pewien warunek.

In [58]:
A = np.random.randint(20, size=(3, 6))
print(A, '\n')
print(np.where(A>5), '\n')
print(np.argwhere(A>5))

[[10  5 10  8  5 19]
 [17  3  8 12 12 10]
 [ 1  7  0 15  2  2]] 

(array([0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2], dtype=int64), array([0, 2, 3, 5, 0, 2, 3, 4, 5, 1, 3], dtype=int64)) 

[[0 0]
 [0 2]
 [0 3]
 [0 5]
 [1 0]
 [1 2]
 [1 3]
 [1 4]
 [1 5]
 [2 1]
 [2 3]]


## Odczytywanie i zapisywanie tablic do/ z pliku

Oprócz powyższych operacji, biblioteka NumPy posiada jeszcze funkcje importujące i eksportujące dane z i do pliku

### Zapisyanie danych - funkcja savetxt

In [67]:
A = np.arange(0.0,5.0,1.0)

print(A)

np.savetxt('test1.out', A, delimiter=',')
with open('test1.out') as f: print(f.read())
    
np.savetxt('test2.out', (A,A,A))   # x,y,z equal sized 1D arrays
with open('test2.out') as f: print(f.read())

np.savetxt('test3.out', A, fmt='%1.4e')   # use exponential notation 
with open('test3.out') as f: print(f.read())

[ 0.  1.  2.  3.  4.]
0.000000000000000000e+00
1.000000000000000000e+00
2.000000000000000000e+00
3.000000000000000000e+00
4.000000000000000000e+00

0.000000000000000000e+00 1.000000000000000000e+00 2.000000000000000000e+00 3.000000000000000000e+00 4.000000000000000000e+00
0.000000000000000000e+00 1.000000000000000000e+00 2.000000000000000000e+00 3.000000000000000000e+00 4.000000000000000000e+00
0.000000000000000000e+00 1.000000000000000000e+00 2.000000000000000000e+00 3.000000000000000000e+00 4.000000000000000000e+00

0.0000e+00
1.0000e+00
2.0000e+00
3.0000e+00
4.0000e+00



### Odczytywanie danych - funkcja loadtxt

In [68]:
with open('test1.out', 'r') as f:
    B = np.loadtxt(f, delimiter=', ')
    
print(B)

[ 0.  1.  2.  3.  4.]


### Jeśli brakuje danych to  np.genfromtxt (https://docs.scipy.org/doc/numpy/reference/generated/numpy.genfromtxt.html#numpy.genfromtxt)

## Wydajność

In [72]:
from timeit import timeit

print(timeit('np.arange(100000).sum()', setup='import numpy as np', number=1000))
print(timeit('sum(range(100000))', number=1000))

0.09712042847599989
2.572290357151717


Źródła:
- http://cs231n.github.io/python-numpy-tutorial/#numpy
- https://www.tutorialspoint.com/numpy/
- https://www.datacamp.com/community/tutorials/python-numpy-tutorial
- https://www.youtube.com/watch?v=h3l4qz76JhQ
- https://www.youtube.com/watch?v=68gDyk3ziIU
- https://www.youtube.com/watch?v=EEUXKG97YRw